# Generated by Django 4.2.30 on 2026-04-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_range', models.CharField(max_length=50)),
                ('qa_name', models.CharField(max_length=100)),
                ('qa_id', models.CharField(max_length=50)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam')], max_length=20)),
                ('line', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('po_no', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=150)),
                ('production_output', models.IntegerField(default=0)),
                ('qty_check', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=100)),
                ('repair_method', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.inspection')),
            ],
        ),
    ]
