# Generated by Django 4.2.30 on 2026-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='shift',
            field=models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=20),
        ),
    ]
