# Generated by Django 4.2.30 on 2026-05-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspection_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionInput',
            fields=[
            ],
            options={
                'verbose_name': 'Input Inspection',
                'verbose_name_plural': 'Input Inspections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inspections.inspection',),
        ),
    ]
