# Generated by Django 4.2.30 on 2026-05-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_inspectioninput'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TIME', 'Time Range'), ('LINE', 'Line'), ('QA_NAME', 'QA Name'), ('QA_ID', 'QA ID'), ('BRAND', 'Brand'), ('MODEL', 'Model'), ('SIZE', 'Size'), ('COLOUR', 'Colour'), ('ITEM', 'Item Name')], max_length=20)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Master Data',
                'verbose_name_plural': 'Master Data',
                'unique_together': {('category', 'value')},
            },
        ),
    ]
