# Generated by Django 4.2.30 on 2026-05-07 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_masterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblingInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('line', models.CharField(max_length=50)),
                ('shift', models.CharField(choices=[('1', 'Shift 1'), ('2', 'Shift 2'), ('3', 'Shift 3')], max_length=20)),
                ('qa_name', models.CharField(max_length=100)),
                ('qa_id', models.CharField(max_length=50)),
                ('po_no', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=50)),
                ('colour', models.CharField(max_length=50)),
                ('inspection_quantity', models.IntegerField(default=0)),
                ('qty_check_hours', models.IntegerField(default=0)),
                ('defect_quantity', models.IntegerField(default=0)),
                ('defect_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblingDefectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='inspections.assemblinginspection')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblingInspectionInput',
            fields=[
            ],
            options={
                'verbose_name': 'Input Assembling',
                'verbose_name_plural': 'Input Assembling',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('inspections.assemblinginspection',),
        ),
    ]
