# Generated by Django 4.2.30 on 2026-05-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_assemblinginspection_assemblingdefectdetail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblingdefectdetail',
            options={'verbose_name': 'Assembling defect detail', 'verbose_name_plural': 'Assembling defect details'},
        ),
        migrations.AlterModelOptions(
            name='assemblinginspection',
            options={'verbose_name': 'Assembling inspection', 'verbose_name_plural': 'Assembling inspections'},
        ),
        migrations.AlterModelOptions(
            name='defectdetail',
            options={'verbose_name': 'Sewing defect detail', 'verbose_name_plural': 'Sewing defect details'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Sewing inspection', 'verbose_name_plural': 'Sewing inspections'},
        ),
        migrations.AlterModelOptions(
            name='inspectioninput',
            options={'verbose_name': 'Input Sewing', 'verbose_name_plural': 'Input Sewing'},
        ),
    ]
