# Generated by Django 4.2.30 on 2026-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_alter_assemblingdefectdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdata',
            options={'verbose_name': 'Master Data Sewing', 'verbose_name_plural': 'Master Data Sewing'},
        ),
        migrations.CreateModel(
            name='AssemblingMasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LINE', 'Line'), ('QA_NAME', 'QA Name'), ('QA_ID', 'QA ID'), ('BRAND', 'Brand'), ('MODEL', 'Model'), ('SIZE', 'Size'), ('COLOUR', 'Colour')], max_length=20)),
                ('value', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Master Data Assembling',
                'verbose_name_plural': 'Master Data Assembling',
                'unique_together': {('category', 'value')},
            },
        ),
    ]
