# Generated by Django 4.2.30 on 2026-05-13 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_alter_masterdata_options_assemblingmasterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblinginspection',
            name='inspection_quantity',
        ),
    ]
